apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crypto-backup-pvc
  namespace: moj
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
  storageClassName: standard
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: crypto-postgres-backup
  namespace: moj
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres:15
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: crypto-user
                      key: password
              command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /backup
                  pg_dump -h crypto-postgres-r.moj.svc.cluster.local \
                          -U crypto_user \
                          crypto_db > /backup/crypto_db-$(date +\%F).sql
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: crypto-backup-pvc