apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: crypto-es
  namespace: logging
spec:
  version: 9.1.4
  image: elasticsearch:9.1.4
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 2Gi
                  cpu: 0.5
                requests:
                  memory: 2Gi
                  cpu: 0.25
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: standard

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: crypto-kb
  namespace: logging
spec:
  version: 9.1.4
  image: kibana:9.1.4
  count: 1
  elasticsearchRef:
    name: crypto-es
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 1
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1024"
